### ISSUE TITLE
Reducing the number of dependencies

### ISSUE THREAD

**Issue by zweihander** [xelaj/mtproto#31]
I think a lot of them can be removed:

github.com/xelaj/go-dry (just write ```if err != nil```, and take some cryptographic stuff)
github.com/xelaj/errs (use our own errors)
github.com/pkg/errors (https://github.com/xelaj/mtproto/pull/15)
github.com/willf/pad (easy copy-paste, 10 lines of code)
github.com/vikyd/zero (reflect in runtime just for zero-value check? 😮 )
github.com/iancoleman/strcase (only camel-case func used in codegen, easy copy-paste)
github.com/asaskevich/EventBus (seems it's just unused)

~~Also we can make the codegen tool as a separate module (so dependencies like jen won't be in the mtproto package itself)~~ [done](https://github.com/xelaj/mtproto/pull/32)

As the Rob Commander Pike said -  [A little copying is better than a little dependency](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=9m28s)

**Comment by ololosha228** [comment]
Okay, so line by line:

`go-dry` — no. this package is **exactly** made for improve code readability, and write more dry-code (**D**on't **R**epeat **Y**ourself, `err != nil` is not dry). Also it contains useful stuff for other things. **I agree** that go-dry do too much stuff for single package, but instead of removing, we can improve go-dry by itself
`errs` — as `go-dry`, it adds **extremely basic** error types and handling. `const someError = errors.New("no way!")` is absolutely shit in go, let's be honest. Also: i agree, that `xelaj/errs` package is so raw, but it's on your way to improve! ;)
`pkg/errors` — we talk about it: it's way more useful than stdlib errors, i don't understand why is go 1.15 exist and `pkg/errors` is still not in stdlib.
`willf/pad` — come on, it is dumb simplest package! golang dependecies handling is realy is for let it go to stay here! (also, i don't understand, why this functionality not in dry. i'll think to add this)
`vikyd/zero` — **HELL YES**, i'll fix it later. this package is pain in the ass after few weeks of experimenting.
`iancoleman/strcase` see [distributed TL schemes](https://github.com/xelaj/mtproto/tree/master/schemes), easy-say, not all actualy are camel cased. Also, strcase helps way more for handling different method names.
`asaskevich/EventBus` —  **well, yes**. but i'll planned to save this for multiple stuff like automatic error handling and getting updates. But maybe this package is not so necessary, and we can make it by simplest channels.

**Comment by ololosha228** [comment]
I'll closing it, cause i noticed you, and try to remove `zero` and `EventBus` in next week.
