### ISSUE TITLE
[FEAT]: add support for WebSocket transports

### ISSUE THREAD

**Issue by aofei** [xelaj/mtproto#78]
#### Is your feature request related to a problem? Please describe.

I think if this project can support MTProto connection over WebSocket, it'll be able to solve the blocking problem of some ISPs.

#### Describe the solution you'd like

For API, maybe we can add a field like `WSEndpoint` (an HTTP URL string) to the [`mtproto.Config`](https://pkg.go.dev/github.com/xelaj/mtproto#Config). If both `ServerHost` and `WSEndpoint` have values, `WSEndpoint` takes precedence.

#### Describe alternatives you've considered

N/A

#### Additional context

https://core.telegram.org/mtproto/transports#websocket

https://core.telegram.org/mtproto/mtproto-transports#transport-obfuscation

**Comment by aofei** [comment]
This one can be assigned to me, I'll try to implement it. But I haven't dug the transport layer code of this project yet. I'm not sure if there will be any difficulties. So it may take some time.

**Comment by quenbyako** [comment]
@aofei yeah, it's great idea, connect to telegram via websockets can improve stability of connection (i hope at least). I'll try to implement uris firstly (one way or another, this stuff must be placed in this package) and make test stand for protocol

:+1: :+1: :+1: :+1:

**Comment by quenbyako** [comment]
@aofei i've created separate package for transport stuff (like transport modes, transport platforms etc), try to push this changes today, but i made only tcp platform, we need to create somehow websocket platform as well.

**Comment by aofei** [comment]
@quenbyako

Sorry, I couldn't find the "transport" package you mentioned. Hasn't it been made public yet?

**Comment by quenbyako** [comment]
@aofei yeah, still working and testing. Unfortunately, i got a lot of work on these days 😩

**Comment by quenbyako** [comment]
@aofei added experimental transport directly to main branch (cuz why not), see latest commits

It's required to cover multiple tests, cause, you know, poor tests better than no tests 🙃

Currently it's not integrated in main mtproto struct because i'm not sure that it doesn't break anything, but i alreday tested new transports, and they seems working well. But, again, i'm not sure and we need to test them.

**Comment by quenbyako** [comment]
new transport package now is using in the main mtproto structure since [this commit](https://github.com/xelaj/mtproto/commit/df86cba1ad26d714e1569b5be9486f4f32be14b4) 🎉🎉🎉🎉

I'll still working on websockets implementation (@aofei your help still can be very helpful), but actualy i hope that this new package already has pretty stable and flexible api.

Also, looks like we fixed #49 issue, now, even with high load of requests id didn't see any panic by bad seqno 🤔 but needs more tests

**Comment by quenbyako** [comment]
Unfortunately, i must close this feature request, cause websockets transport is overcomplicated and obfuscated as well as documentation is. I was experimenting with connection through websockets since april, and still no any positive movement. Mtproto architecture is too sucks.

When we will get official telegram developers support, i promise we will come back to this feature, for me it looks pretty tasty and useful too as for you. But currently it's too hard to implement.
